controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ex01_bundle:
    resource: '../src/Ex01Bundle/Controller/'
    type: attribute

ex02_bundle:
    resource: '../src/Ex02Bundle/Controller'
    type: attribute

ex03_bundle:
    resource: '../src/Ex03Bundle/Controller'
    type: attribute

ex04_bundle:
    resource: '../src/Ex04Bundle/Controller'
    type: attribute

ex05_bundle:
    resource: '../src/Ex05Bundle/Controller'
    type: attribute

ex06_bundle:
    resource: '../src/Ex06Bundle/Controller'
    type: attribute