controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ex01_bundle:
    resource: '../src/Ex01Bundle/Controller/'
    type: attribute

ex02_bundle:
    resource: '../src/Ex02Bundle/Controller'
    type: attribute