twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Ex01Bundle/Resources/views': Ex01
        '%kernel.project_dir%/src/Ex02Bundle/Resources/views': Ex02
        '%kernel.project_dir%/src/Ex03Bundle/Resources/views': Ex03
        '%kernel.project_dir%/src/Ex04Bundle/Resources/views': Ex04
        '%kernel.project_dir%/src/Ex05Bundle/Resources/views': Ex05
        '%kernel.project_dir%/src/Ex06Bundle/Resources/views': Ex06
        '%kernel.project_dir%/src/Ex07Bundle/Resources/views': Ex07

when@test:
    twig:
        strict_variables: true
        